#!/usr/bin/env python
# -*- coding: utf8 -*-

import lxml.html
import mechanize

def get_menus():
    br = mechanize.Browser()

    br.open("http://www.sio.no/")

    br.follow_link(text_regex=r"Mat og drikke")
    br.follow_link(text_regex=r"Dagens middag")

    menus = {}

    menus["Frederikke"] = {
            "Dagens": 2 * [""],
            "Vegetar": 2 * [""],
            "Halal": 2 * [""],
            "Suppe": 5 * [2 * [""]]
            }

    menus["Informatikkafeen"] = {
            "Dagens": 5 * [[""]],
            "Vegetar": 5 * [[""]]
            }

    menus["SV-kafeen"] = {
            "Dagens": 5 * [[""]],
            "Vegetar": 5 * [[""]]
            }

    ### Frederikke ###

    r = br.follow_link(text_regex=r"Frederikke")
    doc = lxml.html.fromstring(unicode(r.read(), encoding="utf8"))
    table = doc.find_class("sioArticleBodyText")[0].findall("table/tbody/tr")

    d, v, h = [[j.text.strip().encode("utf-8") for j in i.findall("td")[1]] for i in table[:5:2]]

    menus["Frederikke"]["Dagens"][0] = d[1:]
    menus["Frederikke"]["Vegetar"][0] = v[0], " ".join(v[1:])
    menus["Frederikke"]["Halal"][0] = h[:2]

    n = 0
    for i in doc.find_class("sioArticleBodyText")[0].findall("font/table/tbody/tr"):
        s = i[-1]
        s = s.text_content()
        s = "".join(s)
        s = s.split(u"\xa0- ")
        s = s[1:]
        s = [t.replace(u"\xa0", "") for t in s]
        s = [t.replace("\n", "") for t in s]
        s = [t.strip() for t in s]
        s = [t.encode("utf-8") for t in s]

        menus["Frederikke"]["Suppe"][n] = s

        n += 1
        if n >= len(menus["Frederikke"]["Suppe"]):
            break

    br.back()

    ### Informatikkafeen ###

    r = br.follow_link(text_regex=r"Informatikk")
    doc = lxml.html.fromstring(unicode(r.read(), encoding="utf8"))
    table = doc.find_class("sioArticleBodyText")[0].findall("table/tbody/tr")

    d = [i.text.encode("utf-8") for i in table[0].findall("td")[2]]

    menus["Informatikkafeen"]["Dagens"] = zip(d[0::2], d[1::2])

    br.back()

    ### SV-kafeen ###

    r = br.follow_link(text_regex=r"SV.kaf")
    doc = lxml.html.fromstring(unicode(r.read(), encoding="utf8"))
    table = doc.find_class("sioArticleBodyText")[0].findall("table/tbody/tr")

    d = [i.text.strip().encode("utf-8") for i in table[0].findall("td")[2][:14]]

    menus["SV-kafeen"]["Dagens"] = [[i] for i in d[0::3][:5]]
    menus["SV-kafeen"]["Vegetar"] = [[i] for i in d[1::3][:5]]

    return menus

def put_html(menus, day):
    print("""<!doctype html>
<head>
    <title>Dagens middag</title>
    <link rel="stylesheet" href="style.css" type="text/css">
    <style>
        .day0 { color: %s; }
        .day1 { color: %s; }
        .day2 { color: %s; }
        .day3 { color: %s; }
        .day4 { color: %s; }
    </style>
</head>
<table>
    <thead>
        <tr>
            <th class="leftmost"></th>
            <th class="leftmost"></th>
            <th class="day0">Mandag</th>
            <th class="day1">Tirsdag</th>
            <th class="day2">Onsdag</th>
            <th class="day3">Torsdag</th>
            <th class="day4">Fredag</th>
        </tr>
    </thead>
    <tbody>
        <tr class="odd">
            <td class="leftmost" rowspan="5">Frederikke</td>
            <td>Åpningstid</td>
            <td class="day0">11:00 - 19:00</td>
            <td class="day1">11:00 - 19:00</td>
            <td class="day2">11:00 - 19:00</td>
            <td class="day3">11:00 - 19:00</td>
            <td class="day4">11:00 - 18:00</td>
        </tr>
        <tr class="odd">
            <td>Dagens</td>
            <td colspan="5"><ul>
                    <li>%s</li>
                    <li>%s</li>
            </ul></td>
        </tr>
        <tr class="odd">
            <td>Vegetar</td>
            <td colspan="5"><ul>
                    <li>%s</li>
                    <li>%s</li>
            </ul></td>
        </tr>
        <tr class="odd">
            <td>Halal</td>
            <td colspan="5">
                <ul>
                    <li>%s</li>
                    <li>%s</li>
                </ul>
            </td>
        </tr>
        <tr class="odd">
            <td>Suppe</td>
            <td class="day0">
                <ul>
                    <li>%s</li>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day1">
                <ul>
                    <li>%s</li>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day2">
                <ul>
                    <li>%s</li>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day3">
                <ul>
                    <li>%s</li>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day4">
                <ul>
                    <li>%s</li>
                    <li>%s</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td class="leftmost" rowspan="3">Informatikkafeen</td>
            <td>Åpningstid</td>
            <td class="day0">11:00 - 17:00</td>
            <td class="day1">11:00 - 17:00</td>
            <td class="day2">11:00 - 17:00</td>
            <td class="day3">11:00 - 17:00</td>
            <td class="day4">11:00 - 15:00</td>
        </tr>
        <tr>
            <td>Dagens</td>
            <td class="day0">
                <ul>
                    <li>%s</li>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day1">
                <ul>
                    <li>%s</li>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day2">
                <ul>
                    <li>%s</li>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day3">
                <ul>
                    <li>%s</li>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day4">
                <ul>
                    <li>%s</li>
                    <li>%s</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>Vegetar</td>
            <td class="day0">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day1">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day2">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day3">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day4">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td class="leftmost" rowspan="3">SV-kafeen</td>
            <td>Åpningstid</td>
            <td class="day0">11:00 - 18:00</td>
            <td class="day1">11:00 - 18:00</td>
            <td class="day2">11:00 - 18:00</td>
            <td class="day3">11:00 - 18:00</td>
            <td class="day4">11:00 - 15:00</td>
        </tr>
        <tr>
            <td>Dagens</td>
            <td class="day0">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day1">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day2">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day3">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day4">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>Vegetar</td>
            <td class="day0">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day1">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day2">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day3">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
            <td class="day4">
                <ul>
                    <li>%s</li>
                </ul>
            </td>
        </tr>
    </tbody>
</table>
<div class="notice">
    <p>Denne siden er laget av Martin Stensgård (mastensg&#64;ping.uio.no).</p>
    <p>Tabellen fins også som <a href="index.json">JSON</a>.</p>
    <p>Kildekoden er tilgjengelig på <a href="http://github.com/mastensg/dagensmiddag">Github</a>.</p>
</div>
    """ % (
            "black" if day == 0 else "#666",
            "black" if day == 1 else "#666",
            "black" if day == 2 else "#666",
            "black" if day == 3 else "#666",
            "black" if day == 4 else "#666",

            menus["Frederikke"]["Dagens"][0][0],
            menus["Frederikke"]["Dagens"][0][1],
            menus["Frederikke"]["Vegetar"][0][0],
            menus["Frederikke"]["Vegetar"][0][1],
            menus["Frederikke"]["Halal"][0][0],
            menus["Frederikke"]["Halal"][0][1],

            menus["Frederikke"]["Suppe"][0][0],
            menus["Frederikke"]["Suppe"][0][1],
            menus["Frederikke"]["Suppe"][1][0],
            menus["Frederikke"]["Suppe"][1][1],
            menus["Frederikke"]["Suppe"][2][0],
            menus["Frederikke"]["Suppe"][2][1],
            menus["Frederikke"]["Suppe"][3][0],
            menus["Frederikke"]["Suppe"][3][1],
            menus["Frederikke"]["Suppe"][4][0],
            menus["Frederikke"]["Suppe"][4][1],

            menus["Informatikkafeen"]["Dagens"][0][0],
            menus["Informatikkafeen"]["Dagens"][0][1],
            menus["Informatikkafeen"]["Dagens"][1][0],
            menus["Informatikkafeen"]["Dagens"][1][1],
            menus["Informatikkafeen"]["Dagens"][2][0],
            menus["Informatikkafeen"]["Dagens"][2][1],
            menus["Informatikkafeen"]["Dagens"][3][0],
            menus["Informatikkafeen"]["Dagens"][3][1],
            menus["Informatikkafeen"]["Dagens"][4][0],
            menus["Informatikkafeen"]["Dagens"][4][1],
            menus["Informatikkafeen"]["Vegetar"][0][0],
            menus["Informatikkafeen"]["Vegetar"][1][0],
            menus["Informatikkafeen"]["Vegetar"][2][0],
            menus["Informatikkafeen"]["Vegetar"][3][0],
            menus["Informatikkafeen"]["Vegetar"][4][0],

            menus["SV-kafeen"]["Dagens"][0][0],
            menus["SV-kafeen"]["Dagens"][1][0],
            menus["SV-kafeen"]["Dagens"][2][0],
            menus["SV-kafeen"]["Dagens"][3][0],
            menus["SV-kafeen"]["Dagens"][4][0],
            menus["SV-kafeen"]["Vegetar"][0][0],
            menus["SV-kafeen"]["Vegetar"][1][0],
            menus["SV-kafeen"]["Vegetar"][2][0],
            menus["SV-kafeen"]["Vegetar"][3][0],
            menus["SV-kafeen"]["Vegetar"][4][0],
            )
    )

def put_text(menus, day):
    print("Frederikke")
    print("==========")
    print("")
    print("Dagens:      %s" % menus["Frederikke"]["Dagens"][0][0])
    print("             %s" % menus["Frederikke"]["Dagens"][0][1])
    print("")
    print("Vegetar:     %s" % menus["Frederikke"]["Vegetar"][0][0])
    print("             %s" % menus["Frederikke"]["Vegetar"][0][1])
    print("")
    print("Halal:       %s" % menus["Frederikke"]["Halal"][0][0])
    print("             %s" % menus["Frederikke"]["Halal"][0][1])
    print("")
    print("Suppe")
    print("-----")
    print("")

    if day == 0:
        print("[1m"),
    print("")
    print("Mandag:      %s" % menus["Frederikke"]["Suppe"][0][0])
    print("             %s[0m" % menus["Frederikke"]["Suppe"][0][1])

    if day == 1:
        print("[1m"),
    print("")
    print("Tirsdag:     %s" % menus["Frederikke"]["Suppe"][1][0])
    print("             %s[0m" % menus["Frederikke"]["Suppe"][1][1])

    if day == 2:
        print("[1m"),
    print("")
    print("Onsdag:      %s" % menus["Frederikke"]["Suppe"][2][0])
    print("             %s[0m" % menus["Frederikke"]["Suppe"][2][1])

    if day == 3:
        print("[1m"),
    print("")
    print("Torsdag:     %s" % menus["Frederikke"]["Suppe"][3][0])
    print("             %s[0m" % menus["Frederikke"]["Suppe"][3][1])

    if day == 4:
        print("[1m"),
    print("")
    print("Fredag:      %s" % menus["Frederikke"]["Suppe"][4][0])
    print("             %s[0m" % menus["Frederikke"]["Suppe"][4][1])

    print("")
    print("Informatikkafeen")
    print("================")
    print("")

    if day == 0:
        print("[1m"),
    print("")
    print("Mandag:      %s[0m" % menus["Informatikkafeen"]["Dagens"][0][0])
    print("             %s[0m" % menus["Informatikkafeen"]["Dagens"][0][1])

    if day == 1:
        print("[1m"),
    print("")
    print("Tirsdag:     %s[0m" % menus["Informatikkafeen"]["Dagens"][1][0])
    print("             %s[0m" % menus["Informatikkafeen"]["Dagens"][1][1])

    if day == 2:
        print("[1m"),
    print("")
    print("Onsdag:      %s[0m" % menus["Informatikkafeen"]["Dagens"][2][0])
    print("             %s[0m" % menus["Informatikkafeen"]["Dagens"][2][1])

    if day == 3:
        print("[1m"),
    print("")
    print("Torsdag:     %s[0m" % menus["Informatikkafeen"]["Dagens"][3][0])
    print("             %s[0m" % menus["Informatikkafeen"]["Dagens"][3][1])

    if day == 4:
        print("[1m"),
    print("")
    print("Fredag:      %s[0m" % menus["Informatikkafeen"]["Dagens"][4][0])
    print("             %s[0m" % menus["Informatikkafeen"]["Dagens"][4][1])

    print("")
    print("SV-kafeen")
    print("=========")
    print("")

    if day == 0:
        print("[1m"),
    print("")
    print("Mandag:      Dagens:     %s[0m" % menus["SV-kafeen"]["Dagens"][0][0])
    print("             Vegetar:    %s[0m" % menus["SV-kafeen"]["Vegetar"][0][0])

    if day == 1:
        print("[1m"),
    print("")
    print("Tirsdag:     Dagens:     %s[0m" % menus["SV-kafeen"]["Dagens"][1][0])
    print("             Vegetar:    %s[0m" % menus["SV-kafeen"]["Vegetar"][1][0])

    if day == 2:
        print("[1m"),
    print("")
    print("Onsdag:      Dagens:     %s[0m" % menus["SV-kafeen"]["Dagens"][2][0])
    print("             Vegetar:    %s[0m" % menus["SV-kafeen"]["Vegetar"][2][0])

    if day == 3:
        print("[1m"),
    print("")
    print("Torsdag:     Dagens:     %s[0m" % menus["SV-kafeen"]["Dagens"][3][0])
    print("             Vegetar:    %s[0m" % menus["SV-kafeen"]["Vegetar"][3][0])

    if day == 4:
        print("[1m"),
    print("")
    print("Fredag:      Dagens:     %s[0m" % menus["SV-kafeen"]["Dagens"][4][0])
    print("             Vegetar:    %s[0m" % menus["SV-kafeen"]["Vegetar"][4][0])

if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        if sys.argv[1] == "--html":
            fmt = "html"
        elif sys.argv[1] == "--json":
            fmt = "json"
        elif sys.argv[1] == "--repr":
            fmt = "repr"
        else:
            sys.stderr.write("Usage: %s [--{html,json,repr}]\n" % sys.argv[0].split("/")[-1])
            sys.exit(1)
    else:
        fmt = "text"

    import time

    weekday = time.localtime().tm_wday
    menus = get_menus()

    if fmt == "html":
        put_html(menus, weekday)
    elif fmt == "json":
        import json
        print json.dumps(menus)
    elif fmt == "repr":
        print(repr(menus))
    else:
        put_text(menus, weekday)
