#!/usr/bin/env python
# -*- coding: utf8 -*-

import json
import sys
import time
import urllib

if __name__ == "__main__":
    import sys

    if len(sys.argv) != 2:
        print("usage: %s output_file" % sys.argv[0])
        exit(1)

    path = sys.argv[1]

    url = time.strftime("http://www.dagensmiddag.net/menyer/%G-%V.json")
    json_response = urllib.urlopen(url).read()
    response = json.loads(json_response)

    weekday = time.localtime().tm_wday

    days = u"Mandag", u"Tirsdag", u"Onsdag", u"Torsdag", u"Fredag", u"Lørdag", u"Søndag"

    htm = """<!doctype html>
<head>
    <title>Dagens middag</title>
    <link rel="stylesheet" href="style.css" type="text/css">
</head>\n"""

    htm += "<table>\n<thead><tr>\n"
    htm += """<th class="leftmost"></th>\n"""
    htm += """<th class="today">%s</th>\n""" % days[weekday]
    htm += "</tr></thead>\n"
    htm += "<tbody>\n"

    row = 0
    for cafe in response["cafes"]:
        name = cafe["name"]
        menu = cafe["menu"]

        if menu[weekday] == []:
            continue

        row_class = ["even", "odd"][row % 2]

        htm += u"""<tr class="%s">\n""" % row_class
        htm += u"""<td class="leftmost">%s</td>\n""" % name

        htm += u"""<td class="today"><ul>\n"""

        for dish in menu[weekday]:
            htm += u"""<li>%s</li>\n""" % dish

        htm += u"""</ul></td>\n"""
        htm += "</tr>\n"

        row += 1

    htm += "</tbody>\n"
    htm += "</table>\n"

    htm += u"""<div class="notice">
    <p>Denne siden er laget av Martin Stensgård (mastensg&#64;ping.uio.no).</p>
    <p>Tabellen er generert basert på <a href="%s">denne JSON-filen</a> fra <a href="menyer">arkivet</a>.
    Filene er på <a href="menyer/schema.json">dette formatet (JSON schema)</a>.</p>
    <p>Kildekoden er tilgjengelig på <a href="http://github.com/mastensg/dagensmiddag">Github</a>.</p>
</div>""" % url

    f = open(path, "w")
    f.write(htm.encode("utf-8"))
    f.close()
